sonar.projectKey=easyqual
sonar.projectName=EasyQual
sonar.projectVersion=1.0

# Path to source directories (required)
sonar.sources=src

# The value of the property must be the key of the language.
sonar.language=js

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude node_modules and build directories from analysis
sonar.exclusions=node_modules/**, dist/**, **/*.test.js, **/*.spec.js
